import { ENUM_PAGINATION_ORDER_DIRECTION_TYPE } from 'src/common/pagination/enums/pagination.enum';

//! Pagination default variable
export const PAGINATION_DEFAULT_PAGE = 1;
export const PAGINATION_DEFAULT_LIMIT = 20;

export const PAGINATION_DEFAULT_ORDER_BY = 'created';
export const PAGINATION_DEFAULT_ORDER_DIRECTION: ENUM_PAGINATION_ORDER_DIRECTION_TYPE =
    ENUM_PAGINATION_ORDER_DIRECTION_TYPE.DESC;

export const PAGINATION_DEFAULT_AVAILABLE_ORDER_BY: string[] = ['created'];
// export const PAGINATION_DEFAULT_AVAILABLE_ORDER_DIRECTION: ENUM_PAGINATION_ORDER_DIRECTION_TYPE[] =
//     Object.values(ENUM_PAGINATION_ORDER_DIRECTION_TYPE);
