"""HDFC Bank statement parser."""

import re
from typing import Optional
from .base import BankParser


class HDFCParser(BankParser):
    BANK_NAME = "HDFC"

    # ── Detection ────────────────────────────────────────────
    def detect(self, full_text: str) -> bool:
        markers = ["hdfc bank", "hdfcbank", "hdfc ltd"]
        text_lower = full_text.lower()
        return any(m in text_lower for m in markers)

    # ── Account Info ─────────────────────────────────────────
    def get_account_info(self, full_text: str) -> dict:
        info: dict = {"bank": self.BANK_NAME}

        # Fast metadata extract using Provided logic
        holder_match = re.search(r'MR\s*\n\s*([A-Z\s]+)\n', full_text)
        if holder_match:
            info["account_holder"] = re.sub(r'\s+', ' ', holder_match.group(1).replace('\n', ' ')).strip()

        acc_no_match = re.search(r'Account No\s*\n?\s*:\s*(\S+)', full_text)
        if acc_no_match:
            info["account_number"] = acc_no_match.group(1).strip()

        from_match = re.search(r'From\s*:\s*(\d{2}/\d{2}/\d{4})', full_text)
        to_match = re.search(r'To\s*:\s*(\d{2}/\d{2}/\d{4})', full_text)
        if from_match and to_match:
            info["period_from"] = from_match.group(1)
            info["period_to"] = to_match.group(1)

        summary_idx = full_text.find("STATEMENT SUMMARY :-")
        if summary_idx != -1:
            summary_block = full_text[summary_idx:summary_idx + 500]
            summ_lines = [l.strip() for l in summary_block.split("\n") if l.strip()]
            amounts = []
            for l in summ_lines:
                if self._is_amount_simple(l) or (l.replace(",", "").isdigit()):
                    amounts.append(self._clean_amount(l))
            
            if len(amounts) >= 6:
                info["opening_balance"] = amounts[0]
                info["closing_balance"] = amounts[5]

        # Standard HDFCFallbacks
        if "account_number" not in info:
            acc_match = re.search(r"(?:Account\s*(?:No|Number|#)[.:\s]*)\s*(\d{8,18})", full_text, re.IGNORECASE)
            if acc_match: info["account_number"] = acc_match.group(1)
            
        if "account_holder" not in info:
            name_match = re.search(r"(?:Account\s*(?:Name|Holder)|Mr\.|Mrs\.|Ms\.)\s*[:\s]*([A-Z][A-Za-z\s.]+)", full_text)
            if name_match: info["account_holder"] = name_match.group(1).strip()

        return info

    # ── Parse Transactions ───────────────────────────────────
    def parse(self, pages: list[dict]) -> list[dict]:
        all_text = "\n".join(p["text"] or "" for p in pages)
        
        info = self.get_account_info(all_text)
        opening_balance = info.get("opening_balance") or 0.0

        # Clean text for HDFC logic (patterns from user script)
        cleaned_text = re.sub(r'Page No \.:.*?Registered Office Address:.*?Mumbai 400013', '\n', all_text, flags=re.DOTALL)
        cleaned_text = re.sub(r'STATEMENT SUMMARY :-.*?Generated By:.*?\d+', '', cleaned_text, flags=re.DOTALL)
        cleaned_text = re.sub(r'={10,} PAGE \d+ ={10,}', '', cleaned_text)
        
        clean_lines = cleaned_text.split("\n")
        transactions = []
        
        i = 0
        while i < len(clean_lines):
            line = clean_lines[i].strip()
            # Date format: 01/01/24 or 01/01/2024
            date_match = re.match(r'^(\d{2}/\d{2}/\d{2,4})(?:\s+(.*))?$', line)
            
            if not date_match:
                i += 1
                continue
            
            date = date_match.group(1)
            # Normalize to DD/MM/YYYY
            parts = date.split("/")
            if len(parts[2]) == 2:
                parts[2] = "20" + parts[2]
            date = "/".join(parts)
            
            narration_parts = [date_match.group(2)] if date_match.group(2) else []
            ref_no = ""
            value_date = ""
            amounts = []
            found = False
            vi = i + 1
            
            # Search for context on next ~20 lines
            for _ in range(20):
                if vi >= len(clean_lines):
                    break
                cl = clean_lines[vi].strip()
                if not cl:
                    vi += 1
                    continue
                
                # Ref No is usually a long digit string
                if re.match(r'^\d{10,}$', cl) and not ref_no:
                    ref_no = cl
                    v_idx = vi + 1
                    # Skip empty lines to find value date
                    while v_idx < len(clean_lines) and not clean_lines[v_idx].strip():
                        v_idx += 1
                    
                    if v_idx < len(clean_lines):
                        vd_match = re.match(r'^(\d{2}/\d{2}/\d{2,4})$', clean_lines[v_idx].strip())
                        if vd_match:
                            value_date = vd_match.group(1)
                            v_parts = value_date.split("/")
                            if len(v_parts[2]) == 2: v_parts[2] = "20" + v_parts[2]
                            value_date = "/".join(v_parts)
                            v_idx += 1
                    
                    # Search for amounts
                    while v_idx < len(clean_lines):
                        al = clean_lines[v_idx].strip()
                        if not al:
                            v_idx += 1
                            continue
                        if self._is_amount_simple(al):
                            amounts.append(self._clean_amount(al))
                            v_idx += 1
                        else:
                            break
                    
                    # Collect remaining narration until next entry or amount
                    while v_idx < len(clean_lines):
                        rl = clean_lines[v_idx].strip()
                        if not rl:
                            v_idx += 1
                            continue
                        if re.match(r'^\d{2}/\d{2}/\d{2}', rl) or re.match(r'^\d{10,}$', rl) or self._is_amount_simple(rl) or rl.startswith("Page No"):
                            break
                        narration_parts.append(rl)
                        v_idx += 1
                    
                    vi = v_idx - 1
                    found = True
                    break
                else:
                    # Not ref_no, must be part of narration
                    if not self._is_amount_simple(cl) and not re.match(r'^\d{2}/\d{2}/\d{2}', cl):
                        narration_parts.append(cl)
                    vi += 1
            
            if found:
                unassigned_amount = None
                cb = 0.0
                if len(amounts) >= 2:
                    cb = amounts[-1]
                    unassigned_amount = amounts[0]
                elif len(amounts) == 1:
                    cb = amounts[0]
                
                transactions.append({
                    "date": date,
                    "description": re.sub(r'\s+', ' ', " ".join(narration_parts)).strip(),
                    "reference": ref_no,
                    "debit": 0.0,
                    "credit": 0.0,
                    "balance": cb,
                    "_unassigned": unassigned_amount
                })
                i = vi + 1
            else:
                i += 1
        
        # Post-process using shared balance inference
        processed_txns = self._post_process_with_balance_inference(transactions, opening_balance)
        return [self._standardize_transaction(t) for t in processed_txns]
